// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("ExerciseOne", "[example]") //Named ExerciseOne, tagged with example
{
    
    //TODO: Set up tests
    REQUIRE(addFive(5)==Approx(10); //within 1 of 5
    REQUIRE(addFive(-2)==Approx(3).margin(5)); //within 5 units of 3
        
}

TEST_CASE("ExerciseTwo", "[example]")
{
    REQUIRE(subtractFive(4)==-1)
    REQUIRE(subtractFive(10)==5)
}

// Notes for teacher: 
// can use variables and libraries
// can use logic operators and loops
// you can run a specific test by using ./tests <TEST CASE NAME HERE>


